# vim: set expandtab:

#
# Github workflow to build container
#
# Dockerfile: expected in top-level directory
#
# Name of image: taken from the action name given below
#       We might just as well be able to take it from
#       $GITHUB_REPOSITORY (which is org_or_user/repo_name)
#
# Image version:
#       Currently a concatenation of the version of the principal package in
#       this image, concatenated with the run number of this action.
#       (This would create issues when deleting an action and recreating
#       it, or when trying to build the same image from another repo -
#       so handle with care).
#
# Registry to push to:
#       Currently ghcr.io, but other registries could be configured
#       as well.
#

name: sle15-sp2-java-11
on:
  workflow_dispatch:
  release:
    types: [created]
  schedule:
    - cron: '39 6 * * *'
jobs:
  build:
    name: build-container
    runs-on: ubuntu-latest
    steps:
      - id: make-credentials
        env:
          SCC_CREDS: ${{ secrets.SCC_CREDENTIALS }}
        run: echo "$SCC_CREDS" > SCCcredentials
      - id: verify
        run: ls -l SCCcredentials
      - uses: docker/setup-qemu-action@v1
      - id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ${{ github.workflow }}/Dockerfile
          push: true
          secret-files: |
            "scc_credentials=./SCCcredentials"
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:3.6.12-${{ github.run_number }}
          build-args: |
            JAVA_VERSION=11
            BUILDID=${{ github.run_number }}
